#!/usr/bin/env python
# -*- coding: utf-8 -*-

from textwrap import dedent


def card(card_id, title, image_url, link_url, desc=None, tag_label=None, media_icon=None, card_size='small', youtube_id=None):
    c_file_name = f'content/home/card_{card_id}.en-US.md'
    content = dedent(f"""\
        ---
        # card {card_id}, size: {card_size}
        title: "{title}"
        image: "{image_url}"
        link_url: "{link_url}"
        tag_label: "{tag_label}"
        """)
    if youtube_id:
        content += f'youtube_id: "{youtube_id}"\n'

    content += dedent(f"""\
        ---
        {desc}
        """)
    with open(c_file_name, 'w') as cf:
        cf.write(content)


card(1,
     card_size='large',
     tag_label='Pocket',
     title='Listen is a new way to read with Pocket',
     desc='With Pocket’s enhanced listen feature, you can read or listen to content on the go.',
     image_url='home/pocket.png',
     link_url='http://getpocket.com/blog/2018/10/introducing-the-new-pocket/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(2,
     tag_label='News',
     title='Firefox on The Cheddar',
     desc='We want to be there to help protect you in your web experience — Denelle Dixon on why we built enhanced tracking protection into Firefox.',
     image_url='home/cheddar.jpg',
     link_url='https://blog.mozilla.org/internetcitizen/2018/11/05/cheddar-firefox-enhanced-tracking-protection/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(3,
     tag_label='Firefox',
     title='Latest Firefox rolls out Enhanced Tracking Protection',
     desc='Get the power to block third-party cookies and effectively stop the most common form of cross-site tracking.',
     image_url='home/firefox.png',
     link_url='https://blog.mozilla.org/blog/2018/10/23/latest-firefox-rolls-out-enhanced-tracking-protection/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(4,
     tag_label='Security',
     title='Data Leeks: Recipes for online privacy',
     desc='Not convinced that a data breach could have real, personal implications? These stories might change your mind.',
     image_url='home/data-leeks.jpg',
     link_url='https://www.dataleeks.com/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(5,
     tag_label='Firefox',
     title='Browser hijacking explained',
     desc='A browser is hijacked by software that has been installed on your system, sometimes intentionally and sometimes without your knowing it.',
     image_url='home/browser-hijacking.png',
     link_url='https://blog.mozilla.org/firefox/your-browser-is-hijacked-now-what/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')

card(6,
     card_size='medium',
     tag_label='Emerging Technologies',
     title='Mixed reality data and consent',
     desc='New kinds of data generated by mixed reality devices present an opportunity to change the conversation about permissions and consent.',
     image_url='home/data-consent.jpg',
     link_url='https://blog.mozvr.com/principles-of-mixed-reality-permissions/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(7,
     card_size='medium',
     tag_label='Firefox',
     title='Save a step when you’re searching',
     desc='Quick and savvy web users know love the multiple ways you can get to search from within Firefox.',
     image_url='home/search.png',
     link_url='https://blog.mozilla.org/firefox/save-a-search-step/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')

card(8,
     card_size='medium',
     tag_label='Grants',
     title='Keeping AI accountable',
     desc='Meet the Creative Media Awards recipients whose projects use art and advocacy to highlight the unintended consequences of AI.',
     image_url='home/ai-accountable.jpg',
     link_url='https://blog.mozilla.org/blog/2018/10/24/keeping-ai-accountable-with-science-fiction-documentaries-and-doodles-plus-225000/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(9,
     card_size='medium',
     tag_label='Grants',
     title='Ethics in computer science competition',
     desc='Up to $3.5 Million in prizes will be awarded. Initial Funding Concepts for Stage 1 are being accepted now through December 13, 2018.',
     image_url='home/ethics.png',
     link_url='https://blog.mozilla.org/blog/2018/10/10/announcing-a-competition-for-ethics-in-computer-science-with-up-to-3-5-million-in-prizes/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')

card(10,
     tag_label='Rapid Fire',
     title='Even better privacy protection',
     desc='Enhanced Tracking Protection in Firefox, plus blocking fingerprinters and abusive cryptocurrency mining in future releases.',
     image_url='home/dolanjski.jpg',
     link_url='https://blog.mozilla.org/internetcitizen/2018/11/02/peter-dolanjski-firefox-enhanced-tracking-protection/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(11,
     tag_label='Grants',
     title='Women Startup Challenge Europe',
     desc='Women-led startup finalists from across Europe pitched their ventures before a panel of tech industry executives. Here are the winners.',
     image_url='home/women-startup.jpg',
     link_url='https://blog.mozilla.org/blog/2018/10/26/women-who-tech-and-mozilla-announce-winners-of-women-startup-challenge-europe/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(12,
     tag_label='Emerging Technologies',
     media_icon='video',
     title='Firefox Reality gets recline mode',
     desc='Now available for download in the Viveport, Oculus and Daydream app stores.',
     image_url='home/reality.jpg',
     link_url='https://blog.mozvr.com/introducing-spoke/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card',
     youtube_id='BcHiFM3m50A')
card(13,
     tag_label='Firefox',
     title='Get the new Firefox Focus',
     desc='The latest version comes with search suggestions, revamped visual design and an under-the-hood surprise for Android users.',
     image_url='home/focus.png',
     link_url='https://blog.mozilla.org/blog/2018/10/02/new-firefox-focus-comes-with-search-suggestions-revamped-visual-design-and-an-under-the-hood-surprise-for-android-users/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(14,
     tag_label='Community',
     title='Show support for Firefox with badges',
     desc='If you’re a Firefox user and want to show your support, we’ve made a collection of badges you can add to your website.',
     image_url='home/badges.png',
     link_url='https://hacks.mozilla.org/2018/10/show-your-support-for-firefox-with-new-badges/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(15,
     tag_label='Developers',
     title='Are you a developer?',
     desc='Get the latest features, fast performance and the development tools you need to build for the open web with Firefox Develop Edition.',
     image_url='home/developer.png',
     link_url='./firefox/developer/')
card(16,
     card_size='medium',
     tag_label='Internet Health',
     title='Data Detox for a healthier digital life',
     desc='With data breaches, creepy ads following you, and years of photos on social media, now is the time for a Data Detox to regain control.',
     image_url='home/data-detox.png',
     link_url='https://blog.mozilla.org/internetcitizen/2017/11/08/data-detox/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
card(17,
     card_size='medium',
     tag_label='Security',
     title='Tips to boost your digital security',
     desc='There is little you can do to prevent a data breach. However, there is plenty you can do to protect yourself in anticipation of one.',
     image_url='home/digital-security.png',
     link_url='https://blog.mozilla.org/internetcitizen/2018/10/01/worried-about-data-breach-protect-passwords/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage&utm_content=card')
